import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("winequality-red.csv")
print("First 5 Rows:")
print(data.head())
print("\nSummary Statistics:")
print(data.describe())
data.hist(bins=50, figsize=(20, 15))
plt.suptitle("Histogram of Wine Quality Features")
plt.savefig("histogram.png")
plt.show()
pd.plotting.scatter_matrix(data, figsize=(20, 20))
plt.suptitle("Scatter Matrix of Wine Quality Features")
plt.savefig("scatter_matrix.png")
plt.show()
